name: checkpoint
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  equatable: ^2.0.7
  result_dart: ^2.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
