name: checkpoint
description: Sistema para gestão de dados de checkpoint em processos multi-etapas com persistência segura e atualizações granulares.
version: 1.0.0
repository: https://github.com/rudsonalves/checkpoint
homepage: https://github.com/rudsonalves/checkpoint
documentation: https://github.com/rudsonalves/checkpoint#readme

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  equatable: ^2.0.7
  result_dart: ^2.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
